igp:
  loopbacks:
  - ipv4:
      local_ip: 10.200.0.1
      netmask: 32
    name: lo0
    vlan: 0
  neighbors:
  - interface: xe-0/0/0
    peer: vqfx2
    speed: 10G
    type: local-core
    vlans:
    - id: 0
      ipv4:
        local_ip: 192.168.2.1
        netmask: 24
        peer_ip: 192.168.2.2
  - interface: xe-0/0/1
    peer: vqfx3
    speed: 10G
    type: local-core
    vlans:
    - id: 0
      ipv4:
        local_ip: 192.168.3.1
        netmask: 24
        peer_ip: 192.168.3.2
