# This task configure the ubuntu machine
- name: Ubuntu setup
  hosts: server
  user: vagrant
  become: yes
  gather_facts: no

  tasks:
    - name: Add ansible ppa
      command: apt-add-repository --yes --update ppa:ansible/ansible

    - name: Update repositories cache and install packages
      apt:
        name: ansible
        update_cache: yes 

    - name: Upgrade all packages to the latest version
      apt:
        name: "*"
        state: latest
        force_apt_get: yes

    - name: Install a list of packages
      apt:
        name: "{{ packages }}"
      vars:
        packages:
        - python
        - python-pip 

    - name: install pip modules
      command: pip install junos-eznc jxmlease    

    - name: mkdir for juniper role
      command: mkdir -p /home/vagrant/.ansible/roles

    - name: install juniper ansible role
      command: ansible-galaxy install -p /home/vagrant/.ansible/roles Juniper.junos    

    - name: sync files for lab
      synchronize:
        src: ../ansible-srv/
        dest: /home/vagrant/    

    - file: dest=/home/vagrant owner=vagrant group=vagrant mode=u=rwX,g=rX,o=rX recurse=yes

    - name: Create noc ssh keys
      copy:
        dest: "/home/vagrant/.ssh/config"
        content: |
          Host vqfx1
             User noc
             PreferredAuthentications publickey
             Port 22
             IdentityFile ~/.ssh/id_rsa          

          Host vqfx2
             User noc
             PreferredAuthentications publickey
             Port 22
             IdentityFile ~/.ssh/id_rsa          

          Host vqfx3
             User noc
             PreferredAuthentications publickey
             Port 22
             IdentityFile ~/.ssh/id_rsa

    - name: insert entries in host file
      blockinfile:
        path: /etc/hosts
        block: |
          192.168.100.20  vqfx1
          192.168.100.21  vqfx2
          192.168.100.22  vqfx3



