igp:
  loopbacks:
  - ipv4:
      local_ip: 10.200.0.2
      netmask: 32
    name: lo0
    vlan: 0
  neighbors:
  - interface: xe-0/0/0
    peer: vqfx1
    speed: 10G
    type: local-core
    vlans:
    - id: 100
      ipv4:
        local_ip: 192.168.2.2
        netmask: 24
        peer_ip: 192.168.2.1
  - interface: xe-0/0/2
    peer: vqfx3
    speed: 10G
    type: local-core
    vlans:
    - id: 100
      ipv4:
        local_ip: 192.168.4.1
        netmask: 24
        peer_ip: 192.168.4.2
